### ISSUE TITLE
TypeError: Struct() argument 1 must be string, not unicode

### ISSUE THREAD

**Issue by qnick** [jcrobak/parquet-python#40]
I've installed this parquet module from pypi and tried to unpack file.
Got this error
```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    for line in parquet.DictReader(fo,columns=['pixel','querystring']):
  File "/usr/lib/python2.7/site-packages/parquet/__init__.py", line 375, in DictReader
    footer = _read_footer(fo)
  File "/usr/lib/python2.7/site-packages/parquet/__init__.py", line 71, in _read_footer
    footer_size = _get_footer_size(fo)
  File "/usr/lib/python2.7/site-packages/parquet/__init__.py", line 64, in _get_footer_size
    tup = struct.unpack("<i", fo.read(4))
TypeError: Struct() argument 1 must be string, not unicode
```
It looks like the constant string "<i" somehow interpreted as unicode string. I've deleted this string and wrote it again with vim. And the error has gone.
But after that python warns me about another unicode string - "<{}i".
I think all such strings should be replaced.
```
$ cat /etc/centos-release
CentOS Linux release 7.2.1511 (Core)
$ python --version
Python 2.7.5
```

**Comment by jcrobak** [comment]
Thanks for the report @qnick. Could you try the code in https://github.com/jcrobak/parquet-python/pull/42 to see if that fixes the issue?

**Comment by qnick** [comment]
Thank you, the unicode error has gone, but threre is another one:
```
[nkutselev@t520 tmp.ShcgE1Eabb]$ python test.py 
ERROR:parquet:parquet.reader requires the fileobj to be opened in binary mode!
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    for line in parquet.DictReader(fo,columns=['pixel','querystring']):
  File "/usr/lib/python2.7/site-packages/parquet-1.1-py2.7.egg/parquet/__init__.py", line 420, in DictReader
    for row in reader(file_obj, columns):
  File "/usr/lib/python2.7/site-packages/parquet-1.1-py2.7.egg/parquet/__init__.py", line 438, in reader
    schema_helper = schema.SchemaHelper(footer.schema)
  File "/usr/lib/python2.7/site-packages/parquet-1.1-py2.7.egg/parquet/schema.py", line 24, in __init__
    assert len(self.schema_elements) == len(self.schema_elements_by_name)
```

self.schema_elements (len == 34):
```
[SchemaElement(scale=None, name=u'hive_schema', field_id=None, repetition_type=None, type_length=None, precision=None, num_children=17, converted_type=None, type=None), SchemaElement(scale=None, name=u'fileid', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=2), SchemaElement(scale=None, name=u'version', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=2), SchemaElement(scale=None, name=u'ip_geocode', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=6, converted_type=None, type=None), SchemaElement(scale=None, name=u'countrycode', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=6), SchemaElement(scale=None, name=u'regionname', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=6), SchemaElement(scale=None, name=u'city', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=6), SchemaElement(scale=None, name=u'postalcode', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=6), SchemaElement(scale=None, name=u'metrocode', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=6), SchemaElement(scale=None, name=u'dmacode', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=6), SchemaElement(scale=None, name=u'timestamp', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=2), SchemaElement(scale=None, name=u'region', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=2), SchemaElement(scale=None, name=u'pixel', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=2), SchemaElement(scale=None, name=u'uuid', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=2), SchemaElement(scale=None, name=u'uuid_exists', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=0), SchemaElement(scale=None, name=u'referingurl', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=6), SchemaElement(scale=None, name=u'useragent', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=6), SchemaElement(scale=None, name=u'ip', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=6), SchemaElement(scale=None, name=u'querystring', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=6), SchemaElement(scale=None, name=u'campaignsinfo', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=1, converted_type=3, type=None), SchemaElement(scale=None, name=u'bag', field_id=None, repetition_type=2, type_length=None, precision=None, num_children=1, converted_type=None, type=None), SchemaElement(scale=None, name=u'array_element', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=6, converted_type=None, type=None), SchemaElement(scale=None, name=u'campaign_id', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=2), SchemaElement(scale=None, name=u'media_types', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=1, converted_type=3, type=None), SchemaElement(scale=None, name=u'bag', field_id=None, repetition_type=2, type_length=None, precision=None, num_children=1, converted_type=None, type=None), SchemaElement(scale=None, name=u'array_element', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=2), SchemaElement(scale=None, name=u'advertiser_id', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=2), SchemaElement(scale=None, name=u'funnel_step_id', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=2), SchemaElement(scale=None, name=u'funnel_step_value', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=2), SchemaElement(scale=None, name=u'track_conversion', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=0), SchemaElement(scale=None, name=u'opted_out', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=0), SchemaElement(scale=None, name=u'event_id', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=6), SchemaElement(scale=None, name=u'dt', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=1), SchemaElement(scale=None, name=u'hr', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=1)]
```
schema_elements_by_name (len == 32):
```
{u'ip': SchemaElement(scale=None, name=u'ip', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=6), u'campaign_id': SchemaElement(scale=None, name=u'campaign_id', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=2), u'funnel_step_value': SchemaElement(scale=None, name=u'funnel_step_value', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=2), u'array_element': SchemaElement(scale=None, name=u'array_element', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=2), u'campaignsinfo': SchemaElement(scale=None, name=u'campaignsinfo', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=1, converted_type=3, type=None), u'city': SchemaElement(scale=None, name=u'city', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=6), u'referingurl': SchemaElement(scale=None, name=u'referingurl', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=6), u'uuid': SchemaElement(scale=None, name=u'uuid', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=2), u'countrycode': SchemaElement(scale=None, name=u'countrycode', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=6), u'event_id': SchemaElement(scale=None, name=u'event_id', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=6), u'ip_geocode': SchemaElement(scale=None, name=u'ip_geocode', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=6, converted_type=None, type=None), u'dmacode': SchemaElement(scale=None, name=u'dmacode', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=6), u'version': SchemaElement(scale=None, name=u'version', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=2), u'timestamp': SchemaElement(scale=None, name=u'timestamp', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=2), u'pixel': SchemaElement(scale=None, name=u'pixel', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=2), u'fileid': SchemaElement(scale=None, name=u'fileid', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=2), u'media_types': SchemaElement(scale=None, name=u'media_types', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=1, converted_type=3, type=None), u'hr': SchemaElement(scale=None, name=u'hr', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=1), u'metrocode': SchemaElement(scale=None, name=u'metrocode', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=6), u'advertiser_id': SchemaElement(scale=None, name=u'advertiser_id', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=2), u'postalcode': SchemaElement(scale=None, name=u'postalcode', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=6), u'dt': SchemaElement(scale=None, name=u'dt', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=1), u'track_conversion': SchemaElement(scale=None, name=u'track_conversion', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=0), u'hive_schema': SchemaElement(scale=None, name=u'hive_schema', field_id=None, repetition_type=None, type_length=None, precision=None, num_children=17, converted_type=None, type=None), u'region': SchemaElement(scale=None, name=u'region', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=2), u'uuid_exists': SchemaElement(scale=None, name=u'uuid_exists', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=0), u'querystring': SchemaElement(scale=None, name=u'querystring', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=6), u'bag': SchemaElement(scale=None, name=u'bag', field_id=None, repetition_type=2, type_length=None, precision=None, num_children=1, converted_type=None, type=None), u'opted_out': SchemaElement(scale=None, name=u'opted_out', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=0), u'useragent': SchemaElement(scale=None, name=u'useragent', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=6), u'regionname': SchemaElement(scale=None, name=u'regionname', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=6), u'funnel_step_id': SchemaElement(scale=None, name=u'funnel_step_id', field_id=None, repetition_type=1, type_length=None, precision=None, num_children=None, converted_type=None, type=2)}
```
Should I create a new issue topic?

**Comment by qnick** [comment]
And another one unicode error:
```
 File "/usr/lib/python2.7/site-packages/parquet-1.1-py2.7.egg/parquet/__init__.py", line 420, in DictReader
    for row in reader(file_obj, columns):
  File "/usr/lib/python2.7/site-packages/parquet-1.1-py2.7.egg/parquet/__init__.py", line 470, in reader
    dict_items)
  File "/usr/lib/python2.7/site-packages/parquet-1.1-py2.7.egg/parquet/__init__.py", line 317, in read_data_page
    bit_width)[:daph.num_values]
  File "/usr/lib/python2.7/site-packages/parquet-1.1-py2.7.egg/parquet/__init__.py", line 267, in _read_data
    values = encoding.read_rle_bit_packed_hybrid(file_obj, bit_width)
  File "/usr/lib/python2.7/site-packages/parquet-1.1-py2.7.egg/parquet/encoding.py", line 230, in read_rle_bit_packed_hybrid
    res += read_bitpacked(io_obj, header, width, debug_logging)
  File "/usr/lib/python2.7/site-packages/parquet-1.1-py2.7.egg/parquet/encoding.py", line 146, in read_bitpacked
    raw_bytes = array.array('B', file_obj.read(byte_count)).tolist()
TypeError: must be char, not unicode
```
Can be fixed with "raw_bytes = array.array(b'B', file_obj.read(byte_count)).tolist()"

**Comment by jcrobak** [comment]
Great, thanks for the feedback. Unfortunately that's not compatible with python 3. I'll try to come up with a fix that works for both.

**Comment by jcrobak** [comment]
@qnick I put together a new version of the patch in #42. Could you try that one?

**Comment by jcrobak** [comment]
I've run the full test suite on centos 7 / python 2.7.5, so I think this is fixed. Unfortunately, I can't test for a regression (see #43).

**Comment by derringdo** [comment]
When I do a "pip install parquet", on a centos 7 machine, the parquet version I get has the issue discussed in this page. However, this issue is fixed in the version I build and install from github. So when will this fix make it into the version installed via "pip" ?
