### ISSUE TITLE
"pip install parquet" doesn't have the fix for Unicode issue

### ISSUE THREAD

**Issue by derringdo** [jcrobak/parquet-python#55]
The following stack trace is due to a bug that, from a different thread on an issue reported last year, was fixed in oct 2016 but this fix doesn't seem to be present in the version you get when you do a "pip install parquet". Since that issue was closed after the fix was posted, I am opening a new issue here so this issue gets attention or I can get some responses:

Traceback (most recent call last):
  File "test.py", line 7, in <module>
    for line in parquet.DictReader(fo,columns=['pixel','querystring']):
  File "/usr/lib/python2.7/site-packages/parquet/__init__.py", line 375, in DictReader
    footer = _read_footer(fo)
  File "/usr/lib/python2.7/site-packages/parquet/__init__.py", line 71, in _read_footer
    footer_size = _get_footer_size(fo)
  File "/usr/lib/python2.7/site-packages/parquet/__init__.py", line 64, in _get_footer_size
    tup = struct.unpack("<i", fo.read(4))
TypeError: Struct() argument 1 must be string,

**Comment by derringdo** [comment]
See https://github.com/jcrobak/parquet-python/issues/40 for the closed issue I reference above.

**Comment by jcrobak** [comment]
I just pushed version 1.2 to pypi.
