### ISSUE TITLE
KeyError: 15

### ISSUE THREAD

**Issue by RunningToTheEdgeOfTheWorld** [jcrobak/parquet-python#61]
Traceback (most recent call last):
  File "pd.py", line 5, in <module>
    for row in parquet.reader(fo,columns=['channel']):
  File "/usr/lib/python2.7/site-packages/parquet/__init__.py", line 459, in reader
    page_header = _read_page_header(file_obj)
  File "/usr/lib/python2.7/site-packages/parquet/__init__.py", line 92, in _read_page_header
    page_header.read(pin)
  File "/usr/lib64/python2.7/site-packages/thriftpy/thrift.py", line 150, in read
    iprot.read_struct(self)
  File "/usr/lib64/python2.7/site-packages/thriftpy/protocol/compact.py", line 250, in read_struct
    fname, ftype, fid = self.read_field_begin()
  File "/usr/lib64/python2.7/site-packages/thriftpy/protocol/compact.py", line 181, in read_field_begin
    return None, self._get_ttype(type), fid
  File "/usr/lib64/python2.7/site-packages/thriftpy/protocol/compact.py", line 134, in _get_ttype
    return TTYPES[byte & 0x0f]
KeyError: 15

**Comment by RunningToTheEdgeOfTheWorld** [comment]
import parquet
import sys
import json
with open(sys.argv[1]) as fo:
   for row in parquet.reader(fo,columns=['id']):
       print(row)
       break

**Comment by RunningToTheEdgeOfTheWorld** [comment]
by the way , I try parquet script, it work...

**Comment by jcrobak** [comment]
make sure you're opening the file in binary mode - that seems like the first thing that might be wrong.

**Comment by RunningToTheEdgeOfTheWorld** [comment]
it work to TTransportException ,but in anthon parquet file, I stil get exception KeyError : 15
in the begining , I thought maybe my file was damaged, but i can read the file use my pyspark

**Comment by RunningToTheEdgeOfTheWorld** [comment]
and i found this package Take up too much memory , the reader generation is not a real generation , it still take all lines to my memory

**Comment by jcrobak** [comment]
thanks for the feedback. i'm going to close this out since you're not ending up using this project - unless you supply more details, I'm not going to be able to debug.
