### ISSUE TITLE
'snappy' is not defined

### ISSUE THREAD

**Issue by Prussian1870** [jcrobak/parquet-python#80]
After installing parquet-1.3.1 on windows 10. The following code was run:

with open("myparquetfile.parquet","rb") as fo:
   for row in parquet.reader(fo, columns=['tconst', 'nconst']):
       print(",".join([str(r) for r in row])

This errored, stack trace below:

Traceback (most recent call last):
  File "c:\working\test.py", line 25, in <module>
    for row in parquet.reader(fo, columns=['tconst', 'nconst']):
  File "C:\Python\Python38\lib\site-packages\parquet\__init__.py", line 464, in reader
    values = read_data_page(file_obj, schema_helper, page_header, cmd,
  File "C:\Python\Python38\lib\site-packages\parquet\__init__.py", line 283, in read_data_page
    raw_bytes = _read_page(file_obj, page_header, column_metadata)
  File "C:\Python\Python38\lib\site-packages\parquet\__init__.py", line 229, in _read_page
    raw_bytes = snappy.decompress(bytes_from_file)
NameError: name 'snappy' is not defined

Thx

**Comment by jcrobak** [comment]
Hi, snappy is listed as an optional dependency, but if your file is compressed with snappy then you must install `parquet-python[snappy]`. See https://github.com/jcrobak/parquet-python#requirements
